/**
 * 事件模板表。
 *
 * ## 写模板的四条规矩
 *
 * 1. **title 必须是人话，且能想象出画面。**
 *    「事业有变动」不收；「被裁员、被动调岗或降职」才收。
 *    检验办法：把它念给不懂命理的人听，对方能不能立刻知道要留意什么。
 * 2. **criterion 必须能被第三者判定。** 它会原样进账本，写不好这条事件就废了。
 * 3. **凶事必须给提前量（advice）。** 只报忧不给对策没有意义 ——
 *    但对策未必是摆件，也可以是「提前谈、留证据、别担保」。
 * 4. **凡涉身体、官非、破财者 minResonance ≥ 2。**
 *    单看一颗七杀就说人要被裁，是取象最常见的失控方式。
 *
 * `noneOf` 表达古法的制化：七杀有食神制则不作凶论、伤官有印制则不冲官。
 * 这是事件层比象意层准的关键 —— 象意只说「七杀能主官非」，
 * 事件层还要看它被制住了没有。
 */

import type { EventTemplate } from './types.js';

export const EVENT_TEMPLATES: readonly EventTemplate[] = [
  /* ───────────── 事业 ───────────── */
  {
    id: 'career.layoff',
    title: '工作上遇裁员、被动调岗或降职',
    domain: '事业',
    valence: '凶',
    allOf: ['七杀'],
    anyOf: ['五黄', '二黑', '三碧', '破军', '化忌'],
    // 食神制杀、印化杀 —— 有制则不作被动凶论
    noneOf: ['食神', '正印'],
    minResonance: 2,
    granularity: '月',
    prior: 0.34,
    classic: '《三命通会·论七杀》：杀无制则为鬼；《紫白诀》五黄二黑加临主损',
    interventionability: '行为可调',
    criterion: '{窗口}内是否发生非本人主动的工作变动（裁员、调岗、降职、项目被撤），以有无正式通知或书面记录为准',
    advice: '提前把手上成果与交接记录留档；这段时间不宜再向公司借支或做长期承诺。',
  },
  {
    id: 'career.promotion',
    title: '升职、转正或拿到新的职衔',
    domain: '事业',
    valence: '吉',
    allOf: ['正官'],
    anyOf: ['正印', '偏印', '一白', '六白', '八白'],
    minResonance: 2,
    granularity: '月',
    prior: 0.42,
    classic: '《渊海子平·正官篇》：官印相生，主贵',
    interventionability: '行为可调',
    criterion: '{窗口}内是否拿到正式的升职、转正或职衔变更文件，以书面通知为准',
    advice: '此段宜主动争取、把成绩摆到台面上；官星怕伤官，少与上级顶撞。',
  },
  {
    id: 'career.jobhop',
    title: '主动跳槽、转行或离开现有体制',
    domain: '事业',
    valence: '中',
    anyOf: ['伤官', '劫财', '破军', '驿马'],
    noneOf: ['正印'],
    minResonance: 2,
    granularity: '月',
    prior: 0.4,
    classic: '《三命通会·论伤官》：伤官见官为祸百端，其人多不居人下',
    interventionability: '择时可避',
    criterion: '{窗口}内是否主动提出离职、换行业或开始新的事业方向，以实际行动（递交辞呈、注册主体）为准',
    advice: '走之前先把下家落定；伤官旺的时段容易一时意气走人，事后追悔。',
  },
  {
    id: 'career.startup',
    title: '自立门户、创业或接手一个新摊子',
    domain: '事业',
    valence: '中',
    allOf: ['七杀'],
    anyOf: ['劫财', '破军', '贪狼', '驿马'],
    minResonance: 2,
    granularity: '年',
    prior: 0.32,
    classic: '《紫微斗数全书》：杀破狼主开创变动',
    interventionability: '行为可调',
    criterion: '{窗口}内是否实际启动了自己的事业（注册、投入本金、正式开张）',
    advice: '七杀主开创也主耗，本金留三成不动；合伙务必先写清楚退出条款。',
  },
  {
    id: 'career.overload',
    title: '工作量骤增、被推上前线扛压力',
    domain: '事业',
    valence: '中',
    allOf: ['七杀'],
    minResonance: 1,
    granularity: '年',
    prior: 0.5,
    classic: '《三命通会·论七杀》：七杀者，制我而不留情',
    interventionability: '行为可调',
    criterion: '{窗口}内工作强度是否明显高于往常（加班、扛新项目、被推去救火）',
    advice: '这段是攒战功的时候，但要盯住身体；七杀耗身，别拿健康换考绩。',
  },

  /* ───────────── 财运 ───────────── */
  {
    id: 'wealth.windfall',
    title: '一笔计划外的进账（奖金、副业、投机得利）',
    domain: '财运',
    valence: '吉',
    allOf: ['偏财'],
    anyOf: ['八白', '九紫', '贪狼', '火星', '铃星', '驿马'],
    minResonance: 2,
    granularity: '月',
    prior: 0.36,
    classic: '《渊海子平·偏财篇》：偏财为众人之财，来去皆速',
    interventionability: '择时可避',
    criterion: '{窗口}内是否有一笔非固定薪资的收入进账（奖金、分红、副业、变现），金额达到你月收入的一半以上',
    advice: '偏财来得快去得也快，进账后先划走一部分锁死，别顺势加码。',
  },
  {
    id: 'wealth.property',
    title: '置产或不动产相关的大笔资金动作',
    domain: '财运',
    valence: '中',
    // 原本 allOf 写了「田宅」—— 那是宫位名，不是任何一层会发出的 token，整条因此永不触发。
    // 可达性测试抓出来的。改以太阴（主田宅）、八白（当元财星）、正财三者择一。
    anyOf: ['太阴', '八白', '正财', '天府'],
    minResonance: 2,
    granularity: '年',
    prior: 0.3,
    classic: '《紫微斗数全书》：太阴主田宅；《紫白诀》八白为当元财星',
    interventionability: '空间可调',
    criterion: '{窗口}内是否发生买房、卖房、装修或大额房产相关支出',
    advice: '动土装修先看当年五黄二黑落在哪一宫，避开再动工。',
  },
  {
    id: 'wealth.loss',
    title: '破财：被借走、担保受累或投资失利',
    domain: '财运',
    valence: '凶',
    allOf: ['劫财'],
    anyOf: ['五黄', '二黑', '七赤', '破军', '化忌'],
    noneOf: ['正官', '七杀'],
    minResonance: 2,
    granularity: '月',
    prior: 0.33,
    classic: '《渊海子平·比劫篇》：劫财夺财，逢官杀制之则吉',
    interventionability: '行为可调',
    criterion: '{窗口}内是否发生非计划的重大资金损失（借出未还、担保被追、投资亏损），金额达到你月收入以上',
    advice: '这段不做担保、不借大额、不上新的杠杆。劫财遇官杀可制，凡事走正式合约。',
  },
  {
    id: 'wealth.bigspend',
    title: '一笔躲不掉的大额支出（装修、置换、赔付）',
    domain: '财运',
    valence: '中',
    anyOf: ['破军', '劫财', '七赤'],
    minResonance: 2,
    granularity: '年',
    prior: 0.35,
    classic: '《紫微斗数全书》：破军为耗星',
    interventionability: '行为可调',
    criterion: '{窗口}内是否有一笔计划外的大额支出（超过月收入两倍）',
    advice: '破军当值的年份，提前留出一笔应急金比事后腾挪省力。',
  },

  /* ───────────── 感情 ───────────── */
  {
    id: 'romance.meet',
    title: '遇到新的感情对象或确定关系',
    domain: '感情',
    valence: '吉',
    anyOf: ['红鸾', '天喜', '桃花', '贪狼', '廉贞'],
    minResonance: 2,
    granularity: '月',
    prior: 0.4,
    classic: '红鸾天喜主婚喜；《紫微斗数全书》贪狼廉贞为桃花之首',
    interventionability: '行为可调',
    criterion: '{窗口}内是否结识了新的交往对象，或与人确定了恋爱关系',
    advice: '红鸾天喜到位是「有机会」不是「自动发生」——这段要多出去走动，机会在人堆里。',
  },
  {
    id: 'romance.marriage',
    title: '论及婚嫁：订婚、结婚或同居',
    domain: '感情',
    valence: '吉',
    allOf: ['红鸾'],
    anyOf: ['天喜', '延年', '正官', '正财', '九紫'],
    minResonance: 2,
    granularity: '年',
    prior: 0.3,
    classic: '红鸾入命主婚配；《八宅明镜》延年主婚姻和合',
    interventionability: '择时可避',
    criterion: '{窗口}内是否订婚、登记结婚、办喜事或开始同居',
    advice: '真要办事，另用择日把日子挑一挑；婚房的主卧尽量避开当年五黄二黑。',
  },
  {
    id: 'romance.breakup',
    title: '感情生变：冷淡、分手或出现第三者',
    domain: '感情',
    valence: '凶',
    anyOf: ['六煞', '五鬼', '伤官', '化忌', '七赤'],
    noneOf: ['延年'],
    minResonance: 2,
    granularity: '年',
    prior: 0.3,
    classic: '《八宅明镜》六煞主感情纠纷与无谓损耗',
    interventionability: '空间可调',
    criterion: '{窗口}内是否发生关系破裂、长期冷战或第三者介入',
    advice: '先看主卧落在哪一宫 —— 六煞、五鬼压主卧是能挪的；挪不了就换床位朝向。',
  },

  /* ───────────── 健康 ───────────── */
  {
    id: 'health.surgery',
    title: '需要动刀或住院处理的伤病',
    domain: '健康',
    valence: '凶',
    // 原本候选只有七杀／破军／白虎，全部只可能来自命层与运层，
    // 凑不出三层，而门槛正是三层 —— 死规则。补上风水层的凶星，门槛才够得着。
    anyOf: ['七杀', '破军', '白虎', '五黄', '二黑', '七赤'],
    minResonance: 3,
    granularity: '年',
    prior: 0.22,
    classic: '《三命通会》七杀属金主刑伤；《紫白诀》五黄正煞，人口常损',
    interventionability: '空间可调',
    criterion: '{窗口}内是否发生需要手术、缝合或住院三天以上的伤病，以就诊记录为准',
    advice: '这不是断症，是提醒做一次体检。同时把睡卧位移出当年五黄二黑所临之宫。',
  },
  {
    id: 'health.chronic',
    title: '慢性问题反复（肠胃、代谢、妇科）',
    domain: '健康',
    valence: '凶',
    allOf: ['二黑'],
    anyOf: ['五黄', '巨门', '化忌'],
    minResonance: 2,
    granularity: '年',
    prior: 0.28,
    classic: '《紫白诀》：二黑病符，主久病缠身',
    interventionability: '空间可调',
    criterion: '{窗口}内是否有慢性不适反复发作、或需长期服药的情况',
    advice: '二黑属土，主卧或常待之处若落此宫，用金泄之（白色、铜器），忌再添火土。',
  },
  {
    id: 'health.injury',
    title: '外伤、跌打或交通意外',
    domain: '意外',
    valence: '凶',
    allOf: ['驿马'],
    anyOf: ['三碧', '七赤', '七杀'],
    minResonance: 2,
    granularity: '月',
    prior: 0.25,
    classic: '《紫白诀》三碧蚩尤主暴戾伤足、七赤主刀伤',
    interventionability: '择时可避',
    criterion: '{窗口}内是否发生外伤、扭挫伤或交通事故（含轻微剐蹭）',
    advice: '驿马动的月份多在路上，行车与器械操作留个心；不赶夜路。',
  },

  /* ───────────── 学业 ───────────── */
  {
    id: 'study.exam',
    title: '考取资格、文凭或通过重要审核',
    domain: '学业',
    valence: '吉',
    anyOf: ['正印', '偏印', '四绿', '文昌'],
    minResonance: 2,
    granularity: '年',
    prior: 0.38,
    classic: '《渊海子平·印绶篇》：印绶主文书功名；四绿文昌主科名',
    interventionability: '空间可调',
    criterion: '{窗口}内是否通过了考试、拿到资格证书或重要审批',
    advice: '书桌摆到当年四绿文昌位，比临时抱佛脚管用。',
  },

  /* ───────────── 迁移 ───────────── */
  {
    id: 'move.relocate',
    title: '搬家、换居所或长期外派',
    domain: '迁移',
    valence: '中',
    allOf: ['驿马'],
    anyOf: ['破军', '天机', '伤官', '劫财'],
    minResonance: 2,
    granularity: '年',
    prior: 0.35,
    classic: '驿马主动；《紫微斗数全书》破军居迁移主动',
    interventionability: '择时可避',
    criterion: '{窗口}内是否实际搬迁了住处或长期办公地点，以是否已经搬入新址为准',
    advice: '真要搬，新居的坐向先看一眼 —— 搬家是少数能整段换掉环境的机会，别浪费。',
  },

  /* ───────────── 官非 ───────────── */
  {
    id: 'legal.dispute',
    title: '合约纠纷、诉讼或被追责',
    domain: '官非',
    valence: '凶',
    // 三碧属风水层、化忌属运层、七杀廉贞属命层 —— 三层够得着
    anyOf: ['七杀', '廉贞', '三碧', '化忌', '五鬼'],
    noneOf: ['食神', '正印', '天医'],
    minResonance: 3,
    granularity: '年',
    prior: 0.2,
    classic: '《渊海子平》杀无制则为鬼；《紫白诀》三碧主官司诉讼',
    interventionability: '择时可避',
    criterion: '{窗口}内是否卷入合约纠纷、诉讼、行政处罚或被正式追责',
    advice: '凡事留书面记录、别口头承诺；三碧当值的年份尤其不要与人争一时之气。',
  },

  /* ───────────── 家庭 / 人丁 ───────────── */
  {
    id: 'family.newborn',
    title: '添丁：怀孕或家中添人口',
    domain: '人丁',
    valence: '吉',
    anyOf: ['天喜', '九紫', '生气', '食神'],
    minResonance: 2,
    granularity: '年',
    prior: 0.28,
    classic: '天喜主添丁；《八宅明镜》生气主升迁添丁；九紫为喜庆星',
    interventionability: '空间可调',
    criterion: '{窗口}内家中是否有人确认怀孕、生产，或有新成员迁入同住',
    advice: '备孕可把卧床移到当年生气或九紫所临之宫，避开五黄二黑。',
  },
  {
    id: 'family.elder',
    title: '长辈健康或家中长者之事',
    domain: '家庭',
    valence: '凶',
    anyOf: ['正印', '偏印', '二黑', '天梁'],
    minResonance: 2,
    granularity: '年',
    prior: 0.26,
    classic: '印为生我者，主父母长辈；《紫白诀》二黑为老母、主疾',
    interventionability: '行为可调',
    criterion: '{窗口}内家中长辈是否有健康状况或需要你出面处理的事',
    advice: '这段多回去看看、催一次体检 —— 这条的提前量只能靠人，摆件帮不上。',
  },

  /* ───────────── 人际 ───────────── */
  {
    id: 'social.gossip',
    title: '口舌是非、被议论或团队摩擦',
    domain: '人际',
    valence: '凶',
    anyOf: ['三碧', '七赤', '伤官', '巨门'],
    noneOf: ['六合'],
    minResonance: 2,
    granularity: '月',
    prior: 0.32,
    classic: '《紫白诀》三碧主口舌是非、七赤主口舌；《紫微斗数全书》巨门主是非',
    interventionability: '行为可调',
    criterion: '{窗口}内是否发生明显的口角、被议论或团队内摩擦',
    advice: '这段少在群里发议论、少做中间人传话；三碧属木，用火（红色）泄之。',
  },
  {
    id: 'social.helper',
    title: '得贵人相助或关键引荐',
    domain: '人际',
    valence: '吉',
    anyOf: ['正印', '天医', '一白', '六白', '天梁'],
    minResonance: 2,
    granularity: '年',
    prior: 0.36,
    classic: '《八宅明镜》天医主遇贵得助；一白主功名人缘',
    interventionability: '行为可调',
    criterion: '{窗口}内是否有人给了你实质性的帮助或关键引荐',
    advice: '贵人是走动出来的 —— 这段主动约人喝茶，比等着强。',
  },

  /* ───────────── 双星断事 ─────────────
   *
   * 以下各条以**双星组合**为条件，而非单星。
   * 玄空的断事在配对上：二五交加 ≠ 二黑 + 五黄 ——
   * 前者是「病符会正关煞」的具体格局，后者只是两颗星恰好在场。
   *
   * `合:` 为宅盘原局组合（风水层，段内常量），
   * `临:` 为流年星飞入该宫与原山向所成之新组合（运层，应期的触发）。
   * 两者并见时即古法所谓「年星临门」，是应期最强的一种。
   *
   * 动气条件不在此表 —— 它由 lifeStore 在发 token 时就已过滤：
   * 无动气之宫根本不发风水 token，故这些模板天然只对「有人在动」的宫成立。
   */

  {
    id: 'combo.crossSword',
    title: '血光、刀伤或与人正面冲突（交剑煞应期）',
    domain: '意外',
    valence: '凶',
    anyOf: ['合:交剑煞', '临:交剑煞'],
    noneOf: ['天医', '延年'],
    minResonance: 2,
    granularity: '年',
    prior: 0.26,
    classic: '《紫白诀》：「六七同宫，交剑煞。」双金相击，主血光刀伤与争斗',
    interventionability: '空间可调',
    criterion: '{窗口}内是否发生外伤流血、需要缝合或手术，或与人爆发正面冲突（含肢体、法律对抗）',
    advice: '交剑之宫忌摆刀剑利器与金属摆件，以水泄金；此方不宜作谈判与争议处理之所。',
  },
  {
    id: 'combo.twoFive',
    title: '重病、久病或家中有人健康出大问题（二五交加应期）',
    domain: '健康',
    valence: '凶',
    anyOf: ['合:二五交加', '合:五二交加', '临:二五交加', '临:五二交加'],
    noneOf: ['天医'],
    minResonance: 2,
    granularity: '年',
    prior: 0.24,
    classic: '《飞星赋》：「二五交加，罹死亡并生疾病。」玄空第一凶组合',
    interventionability: '空间可调',
    criterion: '{窗口}内本人或同住家人是否出现需要长期治疗、住院或手术的健康问题',
    advice: '此方务求静止：不动土、不装修、不设卧床与炉灶；悬六帝钱或纯铜器泄土，忌红色与三角形。',
  },
  {
    id: 'combo.bullFight',
    title: '家人反目、婆媳失和或缠上官司（斗牛煞应期）',
    domain: '官非',
    valence: '凶',
    anyOf: ['合:斗牛煞', '临:斗牛煞'],
    noneOf: ['六合', '天医'],
    minResonance: 2,
    granularity: '年',
    prior: 0.25,
    classic: '《紫白诀》：「斗牛煞起，惹官刑；蚩尤黑曜，斗争频。」',
    interventionability: '空间可调',
    criterion: '{窗口}内是否发生家人长期失和、正式诉讼或需要调解的争议',
    advice: '以红色系通木土之关（红地毯、暖色灯），忌金属与流水；家庭会议与签约避开此方。',
  },
  {
    id: 'combo.fireHeaven',
    title: '火险、目疾或长辈头部之疾（火烧天门应期）',
    domain: '健康',
    valence: '凶',
    anyOf: ['合:火烧天门', '临:火烧天门'],
    minResonance: 2,
    granularity: '年',
    prior: 0.2,
    classic: '《紫白诀》：「七九合辙，常招回禄。」六九火照天门，主长上之灾与头疾',
    interventionability: '空间可调',
    criterion: '{窗口}内是否发生火警、电器起火、眼疾就医，或家中长辈头部与心血管方面的问题',
    advice: '此方忌明火与红色，忌堆放易燃物；用水或金泄之，并检查该方位的电路与炉灶。',
  },
  {
    id: 'combo.wenChang',
    title: '考试得中、文书顺遂或研究出成果（文昌局应期）',
    domain: '学业',
    valence: '吉',
    anyOf: ['合:文昌局', '临:文昌局'],
    minResonance: 2,
    granularity: '年',
    prior: 0.4,
    classic: '《紫白诀》：「一四同宫，准发科名之显。」',
    interventionability: '空间可调',
    criterion: '{窗口}内是否通过考试、拿到证书、论文或作品获得正式认可',
    advice: '把书桌与常用工作位挪到此宫；此方宜静宜明，忌堆杂物与摆放金属利器。',
  },
  {
    id: 'combo.wealthStar',
    title: '进财、置产或事业上一次实质跃升（武曲财局／紫辅同宫应期）',
    domain: '财运',
    valence: '吉',
    anyOf: ['合:武曲财局', '合:紫辅同宫', '临:武曲财局', '临:紫辅同宫', '合:双白财星'],
    minResonance: 2,
    granularity: '年',
    prior: 0.36,
    classic: '《紫白诀》：「辅弼相辉，田园富盛。」六八武曲财局主武贵与财帛',
    interventionability: '空间可调',
    criterion: '{窗口}内是否有一次实质性的进财、置产，或职位与事业规模上的明确跃升',
    advice: '此宫宜开、宜动、宜亮 —— 财位怕压怕静，可设常用出入口、办公位或收银处。',
  },
];
